# https://github.com/golang/go/wiki/GoArm
# https://hub.docker.com/r/arm64v8/alpine/tags
FROM arm64v8/golang:1.21-alpine AS builder

WORKDIR /build
COPY . .
RUN go mod download
RUN go build .

FROM arm64v8/golang:1.21-alpine

WORKDIR /app
COPY --from=builder /build/main .

ENTRYPOINT ["/app/main"]
