version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.amd64
    ports:
      - 8080:8080
    environment:
      - MSSQL_HOSTNAME=localhost
      - MSSQL_PORT=1433
      - MSSQL_USERNAME=sa
      - MSSQL_PASSWORD=P@ssw0rd.123
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd.123
    ports:
      - 1433:1433
